### PR TITLE
move flush memtable logic when learning into rocksdb

### PR DESCRIPTION
**Pull request by qinzuoyan**
1. move flush memtable logic when learning into rocksdb
2. set last_sequence_ to last_durable_seq when recover the db
3. refactor rrdb_service_impl code

### CODE REVIEW

**Comment by imzhenyu** [comment]
see line db_impl.cc:2252, the memtables that do not need filters seem to be dropped?

**Comment by qinzuoyan** [comment]
Oh, sorry, this is uncompleted update, I didn't mean to commit it. Now I'm doing on it.

**Comment by qinzuoyan** [comment]
Done, now mem_state consists of memtable raw entry to avoid unnecessary string copy. We also use filter flag to avoid unnecessary parsing.

**Comment by imzhenyu** [comment]
replication/src/rrdb.server.impl.h 
__out_param::dsn::replication::learn_state& state
need a space in-between, seems to be a old nit.

**Comment by qinzuoyan** [comment]
Done, more fixes have been committed.

**Comment by imzhenyu** [comment]
Seems ok to me

**Pull request merged**
