### PR TITLE
fix last_durable_sequence related code

### PR DESCRIPTION
**Pull request by qinzuoyan**

### CODE REVIEW

**Comment by imzhenyu** [comment]
Great. What is the usage of memtable::last_seqno_ - I don't see it is used somewhere? My understanding is that this can be achieved in current version set. Or you mean when the mem table is during flush, you need a field to remember this value? In that case, can we bookmark this when a mem table is decided to be flushed to avoid the common update for each write operation?

**Comment by qinzuoyan** [comment]
Actually, the memtahble::last_seqno_ is of no use except helping to do some assert:

```
assert(last_seqno_ == 0 || s >= last_seqno);
```

I added it because at the beginning I need a field to remember the value which can be used during flush (just as you say), but later I found it's not necessary because there have been a field 'FileMetaData::largest_seqno'. But I reserved the modification for no hurt. Should I remove it?

**Comment by imzhenyu** [comment]
I guess so. Or we can delay it until we have stabilized the change for replication:)
Sent from my Windows Phone

---

发件人: Zuoyan Qinmailto:notifications@github.com
发送时间: ‎2015/‎7/‎23 10:30
收件人: imzhenyu/rocksdb.replicatedmailto:rocksdb.replicated@noreply.github.com
抄送: Zhenyu Guomailto:imzhenyu@outlook.com
主题: Re: [rocksdb.replicated] fix last_durable_sequence related code (#4)

Actually, the memtahble::last_seqno_ is of no use except helping to do some assert:

```
assert(last_seqno_ == 0 || s >= last_seqno);
```

I added it because at the beginning I need a field to remember the value which can be used during flush (just as you say), but later I found it's not necessary because there have been a field 'FileMetaData::largest_seqno'. But I reserved the modification for no hurt. Should I remove it?

---

**Comment by qinzuoyan** [comment]
No problem, I'll reverse it right now :)

Done.

**Pull request merged**
